"use client";

import { AlertTriangle, Check, ChefHat, ChevronRight, Plus, ShoppingBasket, Snowflake } from "lucide-react";

export type BatchStatus = "planned" | "done" | "skipped";
export type BatchPlan = { enabled: boolean; sundayTime: string; duration: number; statuses: Record<string, BatchStatus> };
export type BatchTask = { id: string; label: string; duration: number; days: number; recipes: string[]; storage: string };
export type ThawTask = { id: string; date: string; timing: string; item: { name: string } };
export type WeekNeed = { name: string; quantity: string; uncertainStock?: boolean };

export function ThawPanel({ tasks, statuses, toggle }: { tasks: ThawTask[]; statuses: Record<string, boolean>; toggle: (id: string) => void }) {
  return <details className="week-fold week-organizer"><summary><Snowflake /><span><b>Décongélation</b><small>{tasks.length ? `${tasks.length} produit${tasks.length > 1 ? "s" : ""} à prévoir` : "Rien à décongeler"}</small></span><ChevronRight /></summary><section className="thaw-board">{tasks.length ? <div className="thaw-list">{tasks.map((task) => <article key={task.id} className={statuses[task.id] ? "done" : ""}><button aria-label={`Marquer la décongélation de ${task.item.name} comme faite`} onClick={() => toggle(task.id)}>{statuses[task.id] ? <Check /> : null}</button><span><b>{task.item.name}</b><small>{task.date} · {task.timing}</small></span><em>{statuses[task.id] ? "Faite" : "À prévoir"}</em></article>)}</div> : <p className="section-empty">Aucune décongélation nécessaire pour les menus actuels.</p>}</section></details>;
}

export function BatchCookingPanel({ plan, sunday, tasks, updatePlan, setStatus }: { plan: BatchPlan; sunday: string; tasks: BatchTask[]; updatePlan: (patch: Partial<BatchPlan>) => void; setStatus: (id: string, status: BatchStatus) => void }) {
  return <details className="week-fold week-organizer"><summary><ChefHat /><span><b>Batch cooking</b><small>{plan.enabled ? `${tasks.length} préparation${tasks.length > 1 ? "s" : ""} · ${sunday}` : "Session non programmée"}</small></span><ChevronRight /></summary><section className="batch-board">
    <div className="batch-head"><div><p className="eyebrow">PRÉPARER À L’AVANCE</p><h3>Mon batch cooking</h3><span>Uniquement les préparations qui font gagner du temps sur plusieurs repas.</span></div><label>Temps disponible<select value={plan.duration} onChange={(event) => updatePlan({ duration: Number(event.target.value) })}><option value="30">30 min</option><option value="60">1 heure</option><option value="90">1 h 30</option><option value="120">2 heures</option></select></label></div>
    <div className="batch-schedule"><label className="batch-schedule-toggle"><input type="checkbox" checked={plan.enabled} onChange={(event) => updatePlan({ enabled: event.target.checked })} /><span>Prévoir cette session le <b>{sunday}</b> après-midi</span></label>{plan.enabled && <label className="batch-time">Heure de début<input type="time" min="12:00" max="19:00" step="900" value={plan.sundayTime} onChange={(event) => updatePlan({ sundayTime: event.target.value })} /></label>}</div>
    {plan.enabled && tasks.length ? <div className="batch-list">{tasks.map((task) => { const status = plan.statuses[task.id] || "planned"; return <article key={task.id} className={status}><button className="batch-check" aria-label={`Marquer ${task.label} comme fait`} onClick={() => setStatus(task.id, status === "done" ? "planned" : "done")}>{status === "done" ? <Check /> : null}</button><span><b>{task.label}</b><small>{task.duration} min · utile pour {task.days} repas · {task.storage}</small><small>{task.recipes.join(" · ")}</small></span><select aria-label={`État de ${task.label}`} value={status} onChange={(event) => setStatus(task.id, event.target.value as BatchStatus)}><option value="planned">Prévue</option><option value="done">Faite</option><option value="skipped">Non faite</option></select></article>; })}</div> : plan.enabled ? <p className="section-empty">Aucune préparation réellement utile à regrouper pour cette semaine.</p> : <p className="section-empty">Active la session seulement si tu souhaites préparer cette semaine à l’avance.</p>}
  </section></details>;
}

export function BreakfastPanel({ people, items, choose }: { people: number; items: Array<{ name: string; shortage?: string }>; choose: (name: string) => void }) {
  const missing = items.filter((item) => item.shortage).length;
  return <details className="week-fold week-organizer"><summary><ShoppingBasket /><span><b>Petits-déjeuners</b><small>{missing ? `${missing} produit${missing > 1 ? "s" : ""} à acheter` : "Tout est disponible"}</small></span><ChevronRight /></summary><div className="breakfast-stock"><div><h3>Petits-déjeuners de la semaine</h3><p>Calculés pour 7 matins et {people} personnes.</p></div><div className="breakfast-grid">{items.map((item) => <button className={item.shortage ? "missing" : "present"} key={item.name} onClick={() => choose(item.name)}>{item.shortage ? <Plus size={14} /> : <Check size={14} />}<b>{item.name}</b><small>{item.shortage ? `manque ${item.shortage}` : "quantité suffisante"}</small></button>)}</div></div></details>;
}

export function WeekShoppingPanel({ needs, inspectStock, addNeed, addAll }: { needs: WeekNeed[]; inspectStock: (name: string) => void; addNeed: (need: WeekNeed) => void; addAll: () => void }) {
  return <details className="week-fold week-shopping-fold"><summary><ShoppingBasket /><span><b>Courses nécessaires</b><small>{needs.length ? `${needs.length} produit${needs.length > 1 ? "s" : ""} à prévoir` : "Rien à acheter"}</small></span><ChevronRight /></summary><div className="week-shopping"><div><h3>Courses nécessaires</h3><p>Uniquement ce qui manque dans tes réserves.</p></div><div className="need-chips">{needs.slice(0, 12).map((need, index) => <button className={need.uncertainStock ? "needs-check" : ""} key={`${need.name}-${index}`} onClick={() => need.uncertainStock ? inspectStock(need.name) : addNeed(need)}>{need.name}<small>{need.quantity}</small>{need.uncertainStock && <em><AlertTriangle size={13} /> Stock à vérifier</em>}</button>)}{needs.length > 12 && <span>+ {needs.length - 12} autres</span>}</div><button className="primary" disabled={!needs.length} onClick={addAll}><ShoppingBasket size={17} />Ajouter la semaine aux courses</button></div></details>;
}
